version: 2

models:
  - name: stg_customers
    description: "Cleaned customer data from raw source"
    columns:
      - name: customer_id
        description: "Primary key for customers"
        tests:
          - unique
          - not_null
          
      - name: email
        description: "Customer email address"
        tests:
          - not_null

  - name: stg_orders
    description: "Cleaned order data from raw source"
    columns:
      - name: order_id
        description: "Primary key for orders"
        tests:
          - unique
          - not_null
          
      - name: customer_id
        description: "Foreign key to customers"
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id