version: 2

sources:
  - name: raw
    description: "Raw data from source systems"
    meta:
      owner: "data_team"
    
    tables:
      - name: customers
        description: "Raw customer data from production database"
        loaded_at_field: created_at
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
        
      - name: orders
        description: "Raw order data from production database"
        loaded_at_field: created_at
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}